### ISSUE TITLE
Support for pip-compile (pip-tools)

### ISSUE THREAD

**Issue by teeberg** [dependencies-io/actor-python-pip#15]
We use pip-compile with a `requirements.in` that is used to generate a `requirements.txt`. Is this workflow supported by this actor?

**Comment by davegaeddert** [comment]
Hey @teeberg, thanks for asking. We're actually getting really close to launching a pretty serious revamp of dependencies.io, including some significant rewrites for most languages. The new python repo is [here](https://github.com/dependencies-io/python) and I think we will finally add pip-tools support: https://github.com/dependencies-io/python/issues/5

Feel free to chime in on that issue and push it along!

**Comment by teeberg** [comment]
thank you for the fast response, will definitely do! :)
